---
# Configuration de Fail2Ban
- name: Configurer Fail2Ban pour protéger contre les attaques
  hosts: all
  become: yes
  tasks:
    - name: Installer Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Copier le fichier de configuration Fail2Ban
      template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
      notify:
        - Redémarrer Fail2Ban

  handlers:
    - name: Redémarrer Fail2Ban
      service:
        name: fail2ban
        state: restarted