---
# Installation de packages de base
- name: Installer les packages de base sur les serveurs
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des packages
      apt:
        update_cache: yes

    - name: Installer les packages nécessaires
      apt:
        name:
          - curl
          - git
          - unzip
          - vim
        state: present